[MPCC-42] (+) add tire ellipse constraints on front and rear wheels
Bauman-Racing-Team/MPCC pull request #85
Opened 2024-02-01 10:56 UTC by DoneZai

2024-02-08 14:39 UTC, KarasevPavel requested changes

2024-02-08 14:39 UTC, KarasevPavel commented on Matlab/parameters/acados_ocp_nlp.json
Вот этот файл, наверное, нужно удалить, он был сгенерирован автоматически и не должен быть в коммите, или я не понимаю что-то

2024-02-08 14:39 UTC, KarasevPavel commented on Matlab/tracks/acados_ocp_nlp.json
Вот этот файл, наверное, нужно удалить, он был сгенерирован автоматически и не должен быть в коммите, или я не понимаю что-то

2024-02-08 14:39 UTC, KarasevPavel commented on Matlab/acados/Acados.m
> +%             obj.ocpOpts.set('nlp_solver_max_iter', 55);
если этот параметр не нужен, его можно просто удалить, чтобы не засорять

2024-02-08 14:39 UTC, KarasevPavel commented on Matlab/acados/Acados.m
> +%             disp(obj.ocpOpts.opts_struct)
если этот параметр не нужен, его можно просто удалить, чтобы не засорять

2024-02-08 14:39 UTC, KarasevPavel commented on Matlab/acados/Acados.m
> +                slacks.upper(:,i) = obj.ocp.get('su',1);
а почему i убрал? значение слэк зависит же от номера итерации на горизонте. Ну или я что-то путаю, но нужен комментарий от тебя

2024-02-08 14:39 UTC, KarasevPavel commented on Matlab/acados/Acados.m
> +                slacks.lower(:,i) = obj.ocp.get('sl',1);
а почему i убрал? значение слэк зависит же от номера итерации на горизонте. Ну или я что-то путаю, но нужен комментарий от тебя

2024-02-08 14:39 UTC, KarasevPavel commented on Matlab/acados/getModel.m
> +    cost_expr_ext_cost = error'*Q*error+input'*R*input-qVs*vs;
наверное, у vs должна быть 2-ая степнь в последнем слагаемом

2024-02-08 14:39 UTC, KarasevPavel commented on Matlab/acados/getModel.m
> +    cost_expr_ext_cost_e = error'*Q*error-qVs*vs;
наверное, у vs должна быть 2-ая степнь в последнем слагаемом

2024-02-08 14:39 UTC, KarasevPavel commented on Matlab/acados/getModel.m
> +    % friction ellipse constraint
Давай перенесем этот код в какую-нибудь функцию типа **initFrictionEllipseConstraint** в файл **mode/Model.m**, потому что все такие вычисления по модели лучше там реализовывать.

Еще давай реализуем функцию **initSimpleFrictionEllipseConstraint** тоже в файле **mode/Model.m**, в котором у нас будет поперечная сила в пятне контакта колеса описана через линейную формулу без модели Пасейки по формуле Fy = cy*a, 

Потом сможем потестировать разные реализации ellipse constraint, используя разные функции

2024-02-08 14:39 UTC, KarasevPavel commented on Matlab/acados/getModel.m
> +    constr_expr_h = [constr_expr_h;(Ffx/2118.04)^2+(Ffy/2030.5)^2;(Frx/2118.04)^2+(Fry/2030.5)^2];
числа из данного выражения нужно занести в какой-то конфигурационный файл и назвать их, чтобы было понятно, что это и откуда

2024-02-08 14:39 UTC, KarasevPavel commented on Matlab/acados/getModel.m
> +    cost_expr_ext_cost = error'*Q*error+input'*R*input-qVs*vs;
у тебя есть переменная vRef, которая раньше использовалась, но сейчас я не вижу, где ты ее используешь? Я бы все же оставил версию с vRef, потому что имея vRef можно легко контролировать ограничение скорости в функции стоимости. Это будет очень актуально на реальном автомобиле, где мы захотим ехать по началу не с максимальной скоростью

2024-02-09 07:49 UTC, DoneZai commented on Matlab/acados/Acados.m
> +                slacks.lower(:,i) = obj.ocp.get('sl',1);
При i=1,  i-1=0, obj.ocp.get('su',i-1) не работает. Я проверил что все слэк при i=1~99 одиноковые, поэтому настройл obj.ocp.get('sl',1);

2024-02-09 11:05 UTC, KarasevPavel requested changes

2024-02-09 11:05 UTC, KarasevPavel commented on Matlab/model/Model.m
> +        function rhs = initCombinedSlipDynamicModel(obj, states, controls)
а это точно должно быть в этом мерже? это не 43 разве?

2024-02-09 11:05 UTC, KarasevPavel commented on Matlab/parameters/car.asv
> +{
а зачем этот файл? у нас же есть конфигурация машины в json? может быть, это из автосохранения случайно добавилось? возможно, стоит добавить все **.asv** файлы в **.gitignore**, чтобы они не добавлялись в индексацию при git add

2024-02-09 11:17 UTC, KarasevPavel commented on Matlab/acados/Acados.m
> +                slacks.lower(:,i) = obj.ocp.get('sl',1);
тогда можно попробовать заменить внешний цикл for на матлабовский цикл заменить, чтобы покомпактнее было

2024-02-09 11:19 UTC, KarasevPavel commented on Matlab/model/Model.m
> +            Ffy = -saf*29700;
тут нужно заменить числовые значения на параметр, вроде, ты его добавил в tire.json

2024-02-09 11:19 UTC, KarasevPavel commented on Matlab/model/Model.m
> +            Fry = -sar*29700;
тут нужно заменить числовые значения на параметр, вроде, ты его добавил в tire.json

2024-02-20 13:17 UTC, KarasevPavel commented
@DoneZai как закончишь с исправленими, отметь, что закончил, чтобы  знал, что можно проверть дальше Для этого тут в мерже кнопка должна быть специальная

2024-03-01 15:06 UTC, KarasevPavel commented on Matlab/plot/@Plot/raceAngles.m
> +    % Ellipse
нужно изспользовать функцию для ellipse constraint из класса Model

2024-03-03 11:53 UTC, DoneZai commented on Matlab/plot/@Plot/raceAngles.m
> +    % Ellipse
Используется класс Моdel в plot_data

2024-03-15 15:12 UTC, KarasevPavel approved these changes

2024-03-15 15:13 UTC, merged