[MPCC-46] (+) Solve the limit on the number of laps
Bauman-Racing-Team/MPCC pull request #90
Opened 2024-04-06 07:45 UTC by DoneZai

Причина проблемы: курсовой угол автомобиля выходит за пределы допустимых значений, в результате чего решатель не может найти приемлемое решение. Это происходит из-за неправильной работы функции unwrapstate в runMPC.  Это странно.

Теперь я перенес ограничение угла в функции unwrapstate в simulator и увеличил ограничение на угол. Теперь все работает нормально.

2024-04-11 17:03 UTC, KarasevPavel commented
едет, но почему-то пишет dist to large примерно с 2000 итерации, надо посмотреть, из-за чего и пофиксить. такое было раньше, когда далеко от трека уезжали

2024-04-11 17:05 UTC, KarasevPavel requested changes
давай попробуем исправить меомент с dist too large

2024-04-29 20:39 UTC, DoneZai commented
1. границы рысканья в границах не должны быть установлены на (-pi,pi), потому что изменения рысканья в сотне шагов, предсказываемые в каждый момент времени, могут быть только непрерывными и будут превышать этот предел.
2. проблема ''dist too large'' должна быть вызвана суммарной ошибкой симулятора для пройденного расстояния. Я решил проблему расстояний, превышающих лимит в один круг, ограничив автомобиль поиском опорных точек только в пределах опорного трека в один круг. В ArcLengthSpline.m расстояние обновляется до ближайшей опорной точки на основе фактического положения автомобиля, так что автомобиль действительно может продолжать движение по трассе.

2024-05-03 15:28 UTC, KarasevPavel commented on Matlab/simulation.m
> +centerLine = ArcLengthSpline(config,parameters.mpcModel);
можно взять из mpc через getTrack()

2024-05-03 15:28 UTC, KarasevPavel commented on Matlab/spline/ArcLengthSpline.m
> +      function sGuess= projectOnSpline(obj,x)
надо вернуть пробел

2024-05-07 18:36 UTC, KarasevPavel commented on Matlab/simulator/Simulator.m
> +        function xNext = simTimeStep(obj,x,u,ts,trackLength)
я так понимаю, теперь не нужно передавать trackLength в метод, потому что у тебя теперь есть поле класса centerline и ты всегда можешь взять tracklength с помощью getLength()

2024-05-07 18:37 UTC, KarasevPavel commented on Matlab/simulator/Simulator.m
> +        function x0 = unwrapState(obj,x0,trackLength)
тут тоже можно trackLength из аргументов убрать, потому что ты можешь всегда взятьь длину из centerline, который у тебя полем объекта лежит

2024-05-10 22:39 UTC, KarasevPavel commented
@DoneZai поменяй только трек обратно на **FSG.mat** в файле симуляции и смержим, остальное все норм

2024-05-11 06:21 UTC, DoneZai commented
> @DoneZai поменяй только трек обратно на **FSG.mat** в файле симуляции и смержим, остальное все норм

Теперь поменял.

2024-05-12 10:21 UTC, DoneZai commented
Изменили unwrapInitialGuess так же, как и в C++, чтобы сделать форму более лаконичной.

2024-05-14 17:41 UTC, KarasevPavel approved these changes

2024-05-14 17:43 UTC, merged