[MPCC-47]  create c++ version
Bauman-Racing-Team/MPCC pull request #93
Opened 2024-05-24 16:36 UTC by DoneZai

[MPCC-47]  create c++ version

2024-06-13 17:27 UTC, KarasevPavel requested changes

2024-06-13 17:27 UTC, KarasevPavel commented on C++/CMakeLists.txt
> +# include_directories(
если не нужны, то нужно удалить лишнее

2024-06-13 17:27 UTC, KarasevPavel commented on C++/CMakeLists.txt
>          # Tests/spline_test.cpp
тесты, наверное, зря удаляешь, они мешают сейчас как-то? их бы лучше поправить и оставить, это ж unit тесты все же, они нелишние

2024-06-13 17:27 UTC, KarasevPavel commented on C++/CMakeLists.txt
>  find_package(Python3 COMPONENTS Interpreter NumPy Development)
почему нет REQUIRED?

2024-06-13 17:27 UTC, KarasevPavel commented on C++/Plotting/plotting.h
> +    // Model model_;
надо удалить, навреное

2024-06-13 17:27 UTC, KarasevPavel commented on C++/Plotting/plotting.h
> +    // Constraints constraints_;
надо удалить, навреное

2024-06-13 17:27 UTC, KarasevPavel commented on C++/Plotting/plotting.cpp
> +:  // model_(Model(Ts,path)),
надо удалить, навреное

2024-06-13 17:27 UTC, KarasevPavel commented on C++/Plotting/plotting.cpp
> +   // constraints_(Constraints(Ts,path)),
надо удалить, навреное

2024-06-13 17:27 UTC, KarasevPavel commented on C++/Plotting/plotting.cpp
> +    // double tire_con_front = (constraints_.tire_con_front_model_)->ForwardZero(x_std_vec)[0];
надо удалить, навреное

2024-06-13 17:27 UTC, KarasevPavel commented on C++/Plotting/plotting.cpp
> +    // double tire_con_rear = (constraints_.tire_con_rear_model_)->ForwardZero(x_std_vec)[0];
надо удалить, навреное

2024-06-13 17:27 UTC, KarasevPavel commented on C++/Plotting/plotting.cpp
> +    // plot_tire_rear.push_back(tire_con_rear);
надо удалить, навреное

2024-06-13 17:27 UTC, KarasevPavel commented on C++/Plotting/plotting.cpp
> +    // plot_tire_front.push_back(tire_con_front);
надо удалить, навреное

2024-06-13 17:27 UTC, KarasevPavel commented on C++/Plotting/plotting.cpp
> +  //   std::vector<double> plot_eps_x;
надо удалить, навреное

2024-06-13 17:27 UTC, KarasevPavel commented on C++/Plotting/plotting.cpp
> +  //   std::vector<double> plot_eps_y;
надо удалить, навреное

2024-06-13 17:27 UTC, KarasevPavel commented on C++/Plotting/plotting.cpp
> +  //   for (double t = 0; t < 2 * M_PI; t += 0.1) {
надо удалить, навреное

2024-06-13 17:27 UTC, KarasevPavel commented on C++/Plotting/plotting.cpp
> +  //     plot_eps_x.push_back(cos(t) * param_.Dr * param_.e_eps);
надо удалить, навреное

2024-06-13 17:27 UTC, KarasevPavel commented on C++/Plotting/plotting.cpp
> +  //     plot_eps_y.push_back(sin(t) * param_.Dr * 1. / param_.e_long * param_.e_eps);
надо удалить, навреное

2024-06-13 17:27 UTC, KarasevPavel commented on C++/Plotting/plotting.cpp
> +  //   }
надо удалить, навреное

2024-06-13 17:27 UTC, KarasevPavel commented on C++/Plotting/plotting.cpp
> +  // plt::figure();
надо удалить, навреное

2024-06-13 17:27 UTC, KarasevPavel commented on C++/Plotting/plotting.cpp
> +  // plt::plot(plot_s,plot_tire_front);
надо удалить, навреное

2024-06-13 17:27 UTC, KarasevPavel commented on C++/Plotting/plotting.cpp
> +  // plt::ylabel("tire_con_f");
надо удалить, навреное

2024-06-13 17:27 UTC, KarasevPavel commented on C++/Plotting/plotting.cpp
> +  // plt::figure();
надо удалить, навреное

2024-06-13 17:27 UTC, KarasevPavel commented on C++/Plotting/plotting.cpp
> +  // plt::plot(plot_s,plot_tire_front);
надо удалить, навреное

2024-06-13 17:27 UTC, KarasevPavel commented on C++/Plotting/plotting.cpp
> +  // plt::xlabel("tire_con_r");
надо удалить, навреное

2024-06-13 17:27 UTC, KarasevPavel commented on C++/Plotting/plotting.h
> +// #include <Model/model.h>
надо удалить, навреное

2024-06-13 17:27 UTC, KarasevPavel commented on C++/Tests/spline_test.cpp
надо бы вернуть, сплайн же остался

2024-06-13 17:27 UTC, KarasevPavel commented on C++/Tests/spline_test.h
надо бы вернуть, сплайн же остался

2024-06-13 17:27 UTC, KarasevPavel commented on C++/env.sh
> +export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/jinlong/baumanracing/MPCC/External/acados/lib
надо бы поправить на универсальный вариант, а то у других это не сработает. можно относительный путь написать, например

2024-06-13 17:27 UTC, KarasevPavel commented on C++/README_NEW.md
> +1. не добавляйте qpoases при компиляции acados
надо изменить имеющийся README в папке C++ или в папке на уровень выше в зависимости от того, кому нужна эта информация: только тем, кто запускает версию С++ или всем в том числе тем, кто запускает версию на matlab

2024-06-13 17:36 UTC, KarasevPavel commented
давай перенесем установку требуемых зависимостей для C++ в скрипт **install.sh**, который находится в корневой директории репозитория и где уже устанавливаются **acados**, **hpipm**, **blasfeo**. Под требуемыми зависимостями я имею в виду **eigen**, **nlohmann/json**, **matplotlib** и все остальное, что требуется для сборки и запуска C++ версии. Ну и ридми в корневой директории репозитория нужно обновить вместе с этим, написав, какие пакеты ставим для C++, там сейчас указаны только **blasfeo** и **hpipm**, вроде.

2024-06-13 17:41 UTC, KarasevPavel commented
надо как-то модифийировать скрипт **install.sh**, который компилирует acados, чтобы не нужно было решать проблему с **libqpOASES_e.so.3.1** вручную

2024-06-18 18:00 UTC, KarasevPavel commented
![изображение](https://github.com/Bauman-Racing-Team/MPCC/assets/48162222/0c683800-b7cb-444f-990f-edecf1f61db8)

matplotlib при этом есть

![изображение](https://github.com/Bauman-Racing-Team/MPCC/assets/48162222/6b0501dc-fb34-4d27-8855-b8549294693f)

2024-06-18 18:52 UTC, DoneZai commented
> ![изображение](https://private-user-images.githubusercontent.com/48162222/340782256-0c683800-b7cb-444f-990f-edecf1f61db8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MzQxMTAsIm5iZiI6MTcxODczMzgxMCwicGF0aCI6Ii80ODE2MjIyMi8zNDA3ODIyNTYtMGM2ODM4MDAtYjdjYi00NDRmLTk5MGYtZWRlY2YxZjYxZGI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDE4MDMzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3NmRjNzU0ODM5YjhhMDBhMjVjMjY5MjA0NWYwYTFlNWY4YmU5NzE1NDhjMTM1M2E2Y2U1NmRiOGM0YjUwYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qlhSRgRrr4KnROT8gHcGqbsbh4GFa6h1gX4LR_6NGB4)
> 
> matplotlib при этом есть
> 
> ![изображение](https://private-user-images.githubusercontent.com/48162222/340782886-6b0501dc-fb34-4d27-8855-b8549294693f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MzQxMTAsIm5iZiI6MTcxODczMzgxMCwicGF0aCI6Ii80ODE2MjIyMi8zNDA3ODI4ODYtNmIwNTAxZGMtZmIzNC00ZDI3LTg4NTUtYjg1NDkyOTQ2OTNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDE4MDMzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4MTEzMDVmNjBiZTk5MDYzOWM4ZTIyODExNTBiYWE3OWQ4ZDQ4YTQyODgzZGU1N2RiM2QyNTg3ZTdiZDBiNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1iVjI-ntcrLmaifkjq51h_Q0I_lrIk6SlC5-gsuutUA)

а это проблема subplot, не знаю как исправится, теперь меняю на plot

2024-06-20 17:00 UTC, KarasevPavel requested changes

2024-06-20 17:00 UTC, KarasevPavel commented on C++/Plotting/plotting.cpp
> +  plt::ylabel("dot{D} [-]");
поправить название

2024-06-20 17:00 UTC, KarasevPavel commented on C++/Plotting/plotting.cpp
> +  plt::ylabel("dot{B} [-]");
поправить название

2024-06-20 17:00 UTC, KarasevPavel commented on C++/Plotting/plotting.cpp
> +  plt::ylabel("dot{delta} [rad/s]");
поправить название

2024-06-20 17:00 UTC, KarasevPavel commented on C++/Plotting/plotting.cpp
> +  plt::ylabel("delta [rad]");
поправить название

2024-06-20 17:00 UTC, KarasevPavel commented on README.md
дописать к Matlab еще и C++

2024-06-20 17:00 UTC, KarasevPavel commented on README.md
Сказать, что версия с ipopt более не поддерживается

2024-06-20 17:00 UTC, KarasevPavel commented on C++/README.md
>  ./install.sh
это нужно убрать, потому что все зависимоси ставятся в скрипте из директоррии выше

2024-06-20 17:00 UTC, KarasevPavel commented on README.md
> +4. [**matplotlib-cpp**](https://github.com/lava/matplotlib-cpp) for plotting the result of the program.
добавить информацию по установке питоновских зависимостей для matplotlib-cpp

2024-06-20 17:00 UTC, KarasevPavel commented on C++/README.md
> +this clones,`acados`,  `matplotlip-cpp`, `nlohmann/json`,  and `eigen` from their git repo, and safes them in a folder External.
это убрать

2024-06-20 17:00 UTC, KarasevPavel commented on C++/README.md
>  Note that `matplotlib-cpp` does also require `Python-2.7` or `Python-3` and `matplotlib`, for more details see (https://github.com/lava/matplotlib-cpp).
перенести в  README выше

2024-06-20 17:02 UTC, KarasevPavel requested changes

2024-06-20 17:02 UTC, KarasevPavel commented on C++/Params/config.json
> +  "track_path": "Params/tracks/FSG_matlab.json"
поменять на FSG

2024-06-20 17:02 UTC, KarasevPavel commented on C++/Params/tracks/FSG_matlab.json
удалить, если не нужен и удалить **FSG_nirajbasnet**

2024-09-25 18:12 UTC, merged